// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owwsxybkewawvarpddtv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93d3N4eWJrZXdhd3ZhcnBkZHR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxMTEwMDYsImV4cCI6MjA1MTY4NzAwNn0.9X0qle2nPZJGeypj3jRu1bIbRzZR_uEDuCHG1XkXum0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);